### ISSUE TITLE
attempt to concatenate spec (a nil value)

### ISSUE THREAD

**Issue by danlamanna** [Demonist/SubSpec#2]
Thanks for the addon!

I'm getting this error on line `266` when trying to concatenate `spec`. Specifically, it happens right after I leave an arena skirmish. It's managed to be pretty reproducible, so let me know if there are any other details you need.

**Comment by Demonist** [comment]
Thank you very  much.
The bug should be fixed in 2.1.3.2 version (8e535474f32a16bb4fa93013937f01876068afd6).
